<?xml version="1.0" encoding="utf-8"?><Database Name="OXCoder" Class="OXUserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN-EJJ7G45UBJM;Initial Catalog=OXCoder;Integrated Security=True;Pooling=False" SettingsObjectName="OXCoder.DBModel.Properties.Settings" SettingsPropertyName="OXCoderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[USER]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>